version: "3"

title: "Yvon dreams on"

description: "A personal experimental site"

baseurl: "/huismusopavontuur"

permalink: pretty

labels:
  about: "Over mij"
  algoritmen: "Algoritmen"
  projects: "Projecten"
  today: "Vandaag…"
  random: "Random"
  contact: "Contact"
  hidden: "Private"

submenus:
  about:
    - name: "Ik in het&nbsp;kort"
      url: "/about/ik/"
    - name: "Werk"
      url: "/about/werk/"
    - name: "Quirks"
      url: "/about/quirks/"

  algoritmen:
    - name: "Ehhh…"
      url: "/algoritmen/huh/"
    - name: "Wow!"
      url: "/algoritmen/wow/"
    - name: "Psycho…"
      url: "/algoritmen/psycho/"

  today:
    - name: "Gewoon vandaag"
      url: "/today/gewoon/"
    - name: "Meteo</br>feiten"
      url: "/today/meteo/"
    - name: "Historisch"
      url: "/today/historisch/"

  projects:
    - name: "Ideeën"
      url: "/projects/ideeen/"
    - name: "Websites & illustraties"
      url: "/projects/screen/"
    - name: "(No) small&nbsp;talk"
      url: "/projects/beyond/"

  random:
    - name: "Muziek"
      url: "/random/music/"
    - name: "Fun facts"
      url: "/random/funfacts/"
    - name: "Antwoorden"
      url: "/random/dontknowyet/"

  hidden:
    - name: "Random taakje"
      url: "/hidden/random"
    - name: "Kalender taakje"
      url: "/hidden/kalender/"
    - name: "Experiment"
      url: "/hidden/experiment/"
