version: "3"

title: "Yvon dreams on"

description: "A personal experimental site"

baseurl: "/huismusopavontuur"

permalink: pretty

labels:
  about: "Over mij"
  ideas: "Huh?!"
  projects: "Projecten"
  today: "Vandaag…"
  random: "Random"
  contact: "Contact"
  hidden: "Private"

submenus:
  about:
    - name: "Ik in het&nbsp;kort"
      url: "/about/ik/"
    - name: "Werk"
      url: "/about/werk/"
    - name: "quirks"
      url: "/about/quirks/"

  ideas:
    - name: "Echt?!"
      url: "/ideas/huh/"
    - name: "Wow!"
      url: "/ideas/wow/"
    - name: "Psycho…"
      url: "/ideas/psycho/"

  projects:
    - name: "Ideeën"
      url: "/projects/ideeen/"
    - name: "Websites & illustraties"
      url: "/projects/screen/"
    - name: "(No) small&nbsp;talk"
      url: "/projects/beyond/"

  hidden:
    - name: "Random taakje"
      url: "/hidden/random"
    - name: "Kalender taakje"
      url: "/hidden/kalender/"
    - name: "Experiment"
      url: "/hidden/experiment/"
